# Deep learning lab course final project.
# Kaggle whale classification.

# R script for analysing the data generated by the augmentation
# hyperband run.

# Run with: Rscript analyse_augmentation.R

# Whereas usually, we need more elaborate models (random forests,
# gaussian bayesian models etc.) to make sense of hyperband run data,
# in this simple case of augmentation parameters, we hope to find
# patterns even with simpler linear models.

# A guide to interpreting the statistics R generates for linear models
# can be found here:
# https://feliperego.github.io/blog/2015/10/23/Interpreting-Model-Output-In-R

# In particular, the R^2 between 0.05 and 0.1 show that the linear
# models tried can only explain a small fraction of the variance in
# the data. This is highly unlikely if we assumed the data to depend
# deterministically on those parameters.

data = read.csv("plots/hyperband_2018-02-08-004129_augmentation/table.csv")
LM = lm(final_val_error ~ height_shift_range + width_shift_range + zoom_range + rotation_range, data = data)
print(summary(LM))
LM = lm(final_val_error ~ height_shift_range * width_shift_range * zoom_range * rotation_range, data = data)
print(summary(LM))
LM = lm(final_val_error ~ height_shift_range + width_shift_range + zoom_range + rotation_range + I(height_shift_range^2) +I( width_shift_range^2) + I(zoom_range^2) + I(rotation_range^2), data = data)
print(summary(LM))
